language: node_js
node_js: 12

jobs:
  include:
    - name: yarn
      env:
      - NEAR_WALLET_ENV=mainnet
      script:
      - yarn lint
      - yarn test
      - yarn build

    - name: fossa
      before_script:
        - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | sudo bash"
      script:
        - fossa analyze
        - fossa test
